"""
Governed Feature Definitions & Feature Registry (Phase 2C)
"""

from typing import Dict, List, Optional
from dataclasses import dataclass


@dataclass
class FeatureDefinition:
    name: str
    description: str
    source_entity: str
    calculation: str
    grain: str
    time_semantics: str
    version: str = "v1"


class FeatureRegistry:
    def __init__(self):
        self._features: Dict[str, FeatureDefinition] = {}
        self._register_default_features()

    def _register_default_features(self) -> None:
        self.register(
            FeatureDefinition(
                name="customer_recency_days_v1",
                description="Days elapsed since customer's most recent order",
                source_entity="dim_customer",
                calculation="DATE_DIFF(CURRENT_DATE(), MAX(order_date), DAY)",
                grain="customer_id",
                time_semantics="order_date",
                version="v1",
            )
        )
        self.register(
            FeatureDefinition(
                name="customer_order_count_v1",
                description="Total historical order count per customer",
                source_entity="dim_customer",
                calculation="COUNT(DISTINCT order_id)",
                grain="customer_id",
                time_semantics="order_date",
                version="v1",
            )
        )
        self.register(
            FeatureDefinition(
                name="customer_total_revenue_v1",
                description="Total monetary revenue generated by customer",
                source_entity="dim_customer",
                calculation="SUM(total_amount)",
                grain="customer_id",
                time_semantics="order_date",
                version="v1",
            )
        )
        self.register(
            FeatureDefinition(
                name="customer_average_order_value_v1",
                description="Average order value per customer",
                source_entity="dim_customer",
                calculation="SUM(total_amount) / NULLIF(COUNT(DISTINCT order_id), 0)",
                grain="customer_id",
                time_semantics="order_date",
                version="v1",
            )
        )
        self.register(
            FeatureDefinition(
                name="product_units_sold_v1",
                description="Total units sold per product",
                source_entity="dim_product",
                calculation="SUM(order_qty)",
                grain="product_id",
                time_semantics="order_date",
                version="v1",
            )
        )
        self.register(
            FeatureDefinition(
                name="supplier_purchase_value_v1",
                description="Total purchase order value per supplier",
                source_entity="dim_supplier",
                calculation="SUM(total_due)",
                grain="supplier_id",
                time_semantics="order_date",
                version="v1",
            )
        )

    def register(self, feature: FeatureDefinition) -> None:
        key = f"{feature.name}"
        self._features[key] = feature

    def get(self, name: str) -> Optional[FeatureDefinition]:
        return self._features.get(name)

    def list_features(self) -> List[FeatureDefinition]:
        return list(self._features.values())
